name: StreamLit
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.2.2=pyhd8ed1ab_0
  - aom=3.9.1=hf036a51_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=h821ce02_5
  - aws-c-cal=0.7.4=hcd44f14_4
  - aws-c-common=0.9.31=ha44c9a9_0
  - aws-c-compression=0.2.19=hcd44f14_4
  - aws-c-event-stream=0.5.0=hc6a372a_0
  - aws-c-http=0.8.10=h178a047_5
  - aws-c-io=0.14.20=hf3ab461_2
  - aws-c-mqtt=0.10.7=hd7707a0_5
  - aws-c-s3=0.7.0=hbfd7bd6_0
  - aws-c-sdkutils=0.1.19=hcd44f14_6
  - aws-checksums=0.1.20=hcd44f14_3
  - aws-crt-cpp=0.29.0=ha8842e2_0
  - aws-sdk-cpp=1.11.407=h84601aa_6
  - azure-core-cpp=1.14.0=h9a36307_0
  - azure-identity-cpp=1.10.0=ha4e2ba9_0
  - azure-storage-blobs-cpp=12.13.0=h3d2f5f1_1
  - azure-storage-common-cpp=12.8.0=h1ccc5ac_1
  - azure-storage-files-datalake-cpp=12.12.0=h86941f0_1
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=h00291cd_2
  - brotli-bin=1.1.0=h00291cd_2
  - brotli-python=1.1.0=py312h5861a67_2
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.2=h32b1619_0
  - ca-certificates=2024.8.30=h8857fd0_0
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.18.0=h37bd5c4_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312hf857d28_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.1=py312hc47a885_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=h0dc2134_0
  - debugpy=1.8.7=py312h5861a67_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=7.1.0=gpl_hf058e7a_103
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.0=py312h3520af0_0
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=hbcb3906_0
  - gdk-pixbuf=2.42.12=ha587570_0
  - gflags=2.2.2=hac325c4_1005
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.7.1=h2790a97_0
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.13=h73e2aa4_1003
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=h098a298_1
  - hdf5=1.14.4=nompi_h57e3b00_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_0
  - imath=3.1.12=h2016aa1_0
  - importlib-metadata=7.2.1=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.29.0=pyh707e725_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jasper=4.2.4=hb10263b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py312hc5c4d5f_0
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20240722.0=cxx17_hac325c4_1
  - libaec=1.1.3=h73e2aa4_0
  - libarrow=18.0.0=h4f78622_1_cpu
  - libarrow-acero=18.0.0=h240833e_1_cpu
  - libarrow-dataset=18.0.0=h240833e_1_cpu
  - libarrow-substrait=18.0.0=h5c0c8cd_1_cpu
  - libasprintf=0.22.5=hdfe23c8_3
  - libass=0.17.3=h5386a9e_0
  - libblas=3.9.0=25_osx64_openblas
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libcblas=3.9.0=25_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.10.1=h58e7537_0
  - libcxx=19.1.3=hf95d169_0
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.6.3=hac325c4_0
  - libffi=3.4.2=h0d85af4_5
  - libgettextpo=0.22.5=hdfe23c8_3
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.82.2=hb6ef654_0
  - libgoogle-cloud=2.30.0=hd00c612_1
  - libgoogle-cloud-storage=2.30.0=h3f2b517_1
  - libgrpc=1.67.1=he6e0b18_0
  - libhwloc=2.11.2=default_hb6fbd3b_1000
  - libiconv=1.17=hd75f5a5_2
  - libintl=0.22.5=hdfe23c8_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=25_osx64_openblas
  - liblapacke=3.9.0=25_osx64_openblas
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.28=openmp_h8869122_0
  - libopencv=4.10.0=headless_py312hf3186f9_10
  - libopenvino=2024.4.0=h84cb933_2
  - libopenvino-auto-batch-plugin=2024.4.0=h92dab7a_2
  - libopenvino-auto-plugin=2024.4.0=h92dab7a_2
  - libopenvino-hetero-plugin=2024.4.0=h14156cc_2
  - libopenvino-intel-cpu-plugin=2024.4.0=h84cb933_2
  - libopenvino-ir-frontend=2024.4.0=h14156cc_2
  - libopenvino-onnx-frontend=2024.4.0=he28f95a_2
  - libopenvino-paddle-frontend=2024.4.0=he28f95a_2
  - libopenvino-pytorch-frontend=2024.4.0=hc3d39de_2
  - libopenvino-tensorflow-frontend=2024.4.0=h488aad4_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=hc3d39de_2
  - libopus=1.3.1=hc929b4f_1
  - libparquet=18.0.0=hc957f30_1_cpu
  - libpng=1.6.44=h4b8f8c9_0
  - libprotobuf=5.28.2=h8b30cf6_0
  - libre2-11=2024.07.02=hd530cb8_1
  - librsvg=2.58.4=h2682814_0
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.47.0=h2f8c449_1
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.21.0=h75589b3_0
  - libtiff=4.7.0=h583c2ba_1
  - libutf8proc=2.8.0=hb7f2c08_0
  - libvpx=1.14.1=hf036a51_0
  - libwebp-base=1.4.0=h10d778d_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.4=h12808cf_2
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.3=hf78d878_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312hbe3f5e4_0
  - matplotlib=3.9.2=py312hb401068_2
  - matplotlib-base=3.9.2=py312h30cc4df_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.12.1=pyhd8ed1ab_0
  - ncurses=6.5=hf036a51_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py312he3a82b2_0
  - opencv=4.10.0=headless_py312hc18783e_10
  - openexr=3.3.1=hb646618_2
  - openh264=2.4.1=h73e2aa4_0
  - openjpeg=2.5.2=h7310d3a_0
  - openssl=3.4.0=hd471939_0
  - orc=2.0.2=hb8ce1e1_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312h98e817e_1
  - pango=1.54.0=h115fe74_2
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h7634a1b_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h683ea77_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.4=h73e2aa4_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - protobuf=5.28.2=py312hae40c12_0
  - psutil=6.1.0=py312h3d0f464_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=he965462_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.10.0=headless_py312hf3908ad_10
  - pyarrow=18.0.0=py312h0be7463_0
  - pyarrow-core=18.0.0=py312h5157fe3_0_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytesseract=0.3.13=pyhd8ed1ab_0
  - python=3.12.7=h8f8b54e_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-decouple=3.8=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312hb553811_1
  - pyzmq=26.2.0=py312h1060d5c_3
  - qhull=2020.2=h3c5361c_5
  - re2=2024.07.02=h2fb0a26_1
  - readline=8.2=h9e318b2_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rpds-py=0.20.1=py312h0d0de52_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=he1e6707_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.39.0=pyhd8ed1ab_0
  - svt-av1=2.3.0=h97d8b74_0
  - tbb=2022.0.0=h0ec6371_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py312hb553811_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - tzlocal=5.2=py312hb401068_1
  - unicodedata2=15.1.0=py312h3d0f464_1
  - urllib3=2.2.3=pyhd8ed1ab_0
  - validators=0.34.0=pyhd8ed1ab_0
  - watchdog=5.0.3=py312hb553811_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.11=h00291cd_1
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=he4ceba3_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.23.0=py312h7122b0e_1
  - zstd=1.5.6=h915ae27_0
  - pip:
      - aioice==0.9.0
      - aiortc==1.9.0
      - av==12.3.0
      - cryptography==43.0.3
      - dnspython==2.7.0
      - google-crc32c==1.6.0
      - ifaddr==0.2.0
      - opencv-contrib-python==4.10.0.84
      - pyee==12.0.0
      - pylibsrtp==0.10.0
      - pyopenssl==24.2.1
      - scipy==1.14.1
      - streamlit-aggrid==1.0.5
      - streamlit-camera-input-live==0.2.0
      - streamlit-drawable-canvas==0.9.3
      - streamlit-image-coordinates==0.2.0
      - streamlit-webrtc==0.47.9
prefix: /Users/keeganmoseley/miniconda3/envs/StreamLit
